name: BuildWatch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm i

      - name: Run Build
        run: node run.cjs